package com.gms.entity;

import com.gms.enums.TicketStatus;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "sub_tickets", indexes = {
    @Index(name = "idx_sub_ticket_main", columnList = "main_ticket_id"),
    @Index(name = "idx_sub_ticket_employee", columnList = "employee_id"),
    @Index(name = "idx_sub_ticket_status", columnList = "status")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SubTicket {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Auto-generated by the system
    @Column(name = "ticket_number", unique = true, nullable = false, length = 50)
    private String ticketNumber;

    @NotNull(message = "Main ticket is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "main_ticket_id", nullable = false)
    private MainTicket mainTicket;

    @NotNull(message = "Employee is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "employee_id", nullable = false)
    private User employee;

    @NotNull(message = "Status is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private TicketStatus status = TicketStatus.ASSIGNED;

    @Column(columnDefinition = "TEXT")
    private String notes;

    // Scoring system
    @Column(name = "completion_factor")
    private Double completionFactor; // 0.0 to 1.0

    @Column(name = "quality_factor")
    private Double qualityFactor; // 0.0 to 1.0

    @Column(name = "score")
    private Double score; // Calculated: weight × completionFactor × qualityFactor

    // Approval flow
    @Column(name = "approved")
    @Builder.Default
    private Boolean approved = false;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "approved_by")
    private User approvedBy;

    @Column(name = "approved_at")
    private LocalDateTime approvedAt;

    @Column(name = "admin_review_notes", columnDefinition = "TEXT")
    private String adminReviewNotes;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @Column(name = "completed_at")
    private LocalDateTime completedAt;
}
